name: Build syllabus PDF
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install -y python3-pygments
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: portafolio.tex
          latexmk_shell_escape: true
      - name: Move PDF to output directory
        run: |
          mkdir output
          mv portafolio.pdf output/
      - name: Push contents of output/ to an orphan branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: portafolio
          force_orphan: true
